services:
  db:
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_DB: optimap
      POSTGRES_USER: optimap
      POSTGRES_PASSWORD: optimap
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: postgis://optimap:optimap@db:5432/optimap?sslmode=disable
      OPTIMAP_CACHE: "dummy"
      OPTIMAP_DEBUG: "True"
    volumes:
      - ".:/code:ro"
      - "./fixtures:/fixtures:ro"
    ports:
      - "8000:8000"
    depends_on:
      - db

  djangoq:
    build: .
    environment:
      DATABASE_URL: postgis://optimap:optimap@db:5432/optimap?sslmode=disable
      OPTIMAP_CACHE: "dummy"
      OPTIMAP_DEBUG: "True"
    command: python manage.py qcluster
    volumes:
      - ".:/code:ro"
    ports:
      - "8000:8001"
    depends_on:
      - db

  webserver:
    image: nginx:1.27-alpine
    volumes:
      - "./etc/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  db_data:
    driver: local
