services:
  db:
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_DB: optimap
      POSTGRES_USER: optimap
      POSTGRES_PASSWORD: optimap
      #POSTGRES_PASSWORD_FILE: database_password
    #ports:
    #  - "5432:5432"
    volumes:
      - optimap-volume:/var/lib/postgresql/data
    #secrets:
    #  - database_password

  app:
    build: .
    environment:
      #see local .env file on the server
      DATABASE_URL: postgis://optimap:optimap@db:5432/optimap?sslmode=disable
      OPTIMAP_DEBUG: "False"
    volumes:
      - "./optimap/.env:/code/optimap/.env:ro"
    #ports:
    #  - "8000:8000"
    depends_on:
      - db
    restart: always

  djangoq:
    build: .
    environment:
      #see local .env file on the server
      DATABASE_URL: postgis://optimap:optimap@db:5432/optimap?sslmode=disable   
    entrypoint: ["python"] # do not run manage-and-run.sh script
    command: ["manage.py", "qcluster"]
    volumes:
      - "./optimap/.env:/code/optimap/.env:ro"
    depends_on:
      - db
      - app
    restart: always

  webserver:
    image: nginx:1.27-alpine
    volumes:
      - "./etc/nginx.deploy.conf:/etc/nginx/nginx.conf:ro"
      - "./certbot/www/:/var/www/certbot/:ro"
      - "./certbot/conf/:/etc/nginx/ssl/:ro"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
       - app
    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      - "./certbot/www/:/var/www/certbot/:rw"
      - "./certbot/conf/:/etc/letsencrypt/:rw"

volumes:
  optimap-volume:
    driver: local

#secrets:
#  database_password:
#    file: /var/www/komet/database_password.secret
