version: "3.9"
   
services:
  db:
    image: postgis/postgis:14-3.3
    #volumes:
    #  - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=optimetaPortal
      - POSTGRES_USER=optimeta
      - POSTGRES_PASSWORD=optimeta
  web:
    build: .
    environment:
      - DATABASE_URL=postgis://optimeta:optimeta@db:5432/optimetaPortal?sslmode=disable
    # overwrite app code for development:
    volumes:
    #  - .:/code
    # load test data
      - ./fixtures/:/fixtures
    ports:
      - "8000:8000"
    depends_on:
      - db
