version: "3.9"
   
services:
  db:
    image: postgis/postgis:14-3.3
    #volumes:
    #  - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=optimap
      - POSTGRES_USER=optimap
      - POSTGRES_PASSWORD=optimap
  web:
    build: .
    environment:
      - DATABASE_URL=postgis://optimap:optimap@db:5432/optimap?sslmode=disable
    # overwrite app code for development:
    #volumes:
    #  - .:/code
    # mount test data 
    #  - ./fixtures/:/fixtures
    ports:
      - "8000:8000"
    depends_on:
      - db
