# fly.toml app configuration file generated for optimap on 2023-11-07T01:40:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "optimap"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "sh release_command.sh"

[env]
  CSRF_TRUSTED_ORIGINS = "https://optimap.science"
  OPTIMAP_ALLOWED_HOST = "optimap.science,www.optimap.science,optimap.fly.dev"
  OPTIMAP_DEBUG = "false"
  OPTIMAP_EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
  OPTIMAP_EMAIL_HOST = "smtp.ionos.de"
  OPTIMAP_EMAIL_HOST_IMAP = "imap.ionos.de"
  OPTIMAP_EMAIL_HOST_USER = "login@optimap.science"
  OPTIMAP_EMAIL_IMAP_SENT_FOLDER = "Gesendete Objekte"
  OPTIMAP_EMAIL_PORT_IMAP = "993"
  OPTIMAP_EMAIL_PORT_SMTP = "587"
  OPTIMAP_EMAIL_USE_TLS = "true"
  OPTIMAP_LOGGING_LEVEL = "DEBUG"
  DJANGO_LOGGING_LEVEL = "WARNING"
  PORT = "8000"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
