# Generated by Django 4.0.5 on 2025-01-20 10:32

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_timeperiod_enddate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-id'], 'verbose_name': 'publication', 'verbose_name_plural': 'publications'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['user_name'], 'verbose_name': 'subscription', 'verbose_name_plural': 'subscriptions'},
        ),
        migrations.AddField(
            model_name='publication',
            name='journal_identifier',
            field=models.CharField(blank=True, help_text='Unique identifier (ISSN or OpenAlex ID) for the journal', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal_name',
            field=models.CharField(blank=True, help_text='Name of the journal or source', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal_openalex_url',
            field=models.URLField(blank=True, help_text='OpenAlex URL for the journal or source', max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal_publisher',
            field=models.CharField(blank=True, help_text='Publisher of the journal', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=models.TextField(blank=True, help_text='Abstract of the publication', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(help_text='Digital Object Identifier (DOI)', max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, help_text='Spatial data associated with the publication', null=True, srid=4326, verbose_name='Publication geometry/ies'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='provenance',
            field=models.TextField(blank=True, help_text='Provenance or source of this record', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publicationDate',
            field=models.DateField(blank=True, help_text='Date of publication', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='source',
            field=models.CharField(blank=True, help_text='Source (e.g., journal, conference, preprint repository)', max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published'), ('t', 'Testing'), ('w', 'Withdrawn'), ('h', 'Harvested')], default='d', help_text='Publication status', max_length=1),
        ),
        migrations.AlterField(
            model_name='publication',
            name='timeperiod_enddate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024, null=True), blank=True, help_text="End date(s) for the publication's time period", null=True, size=None),
        ),
        migrations.AlterField(
            model_name='publication',
            name='timeperiod_startdate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1024, null=True), blank=True, help_text="Start date(s) for the publication's time period", null=True, size=None),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.TextField(blank=True, help_text='Title of the publication', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='url',
            field=models.URLField(blank=True, help_text='URL to the publication', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp'),
        ),
        migrations.AlterField(
            model_name='source',
            name='harvest_interval_minutes',
            field=models.IntegerField(default=4320, help_text='Harvest interval in minutes'),
        ),
        migrations.AlterField(
            model_name='source',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp'),
        ),
        migrations.AlterField(
            model_name='source',
            name='last_harvest',
            field=models.DateTimeField(auto_now_add=True, help_text='Last time the source was harvested', null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='url_field',
            field=models.URLField(help_text='URL of the source', max_length=999),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(help_text='Name of the subscription', max_length=4096),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='search_area',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, help_text='Geographical area for the subscription', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='search_term',
            field=models.CharField(help_text='Search term', max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='timeperiod_enddate',
            field=models.DateField(help_text="End date for the subscription's time period", null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='timeperiod_startdate',
            field=models.DateField(help_text="Start date for the subscription's time period", null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user_name',
            field=models.CharField(help_text='User name associated with the subscription', max_length=4096),
        ),
    ]
